### ISSUE TITLE
Unreliable fullscreen option for Gosu on PocketCHIP

### ISSUE THREAD

**Issue by sci-phi** [gosu/gosu#404] opened 2017-05-21 13:28 UTC
I am attempting to use Gosu on PocketCHIP which has a 480x272 screen.

Debian GNU/Linux 8 
libsdl2-dev/stable,now 2.0.2+dfsg1-6 armhf [installed]
ruby 2.4.1p111 (2017-03-22 revision 58053) [armv7l-linux-eabihf] [via RbEnv/Ruby-Build on-device]
gosu (0.12.0)

The problem I have is that thes cript does not respect the fullscreen option in the super() initializer on Gosu::Window.

Via trial and error I can occasionally retry and get fullscreen, but this is obviously not desirable, and seems to only work if I request a larger screen, so that scaling sometimes does the right thing I guess. Either way, the same code does not do the same thing on any two runs in a row. 

[gosu-fullscreen.rb.txt](https://github.com/gosu/gosu/files/1017032/gosu-fullscreen.rb.txt)

When running the attached demo file, I do get some LibGL errors RE: "sun4i-drm-dri.so", but not sure if relevant to window dimensions.

Console errors :
```
libGL error: MESA-LOADER: malformed or no PCI ID
libGL error: unable to load driver: sun4i-drm_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: sun4i-drm
```

Please advise if there is some setup trick that I am missing to make this work better... 
Thanks!

**Comment by sci-phi** [comment] 2017-05-21 13:35
FYI : I checked with Gosu.screen_width and Gosu.screen_height which reported the expected 480, 272 dimensions.

**Comment by sci-phi** [comment] 2017-05-21 13:37
Per this thread, the sun4i errors seem to be ignorable ...
https://bbs.nextthing.co/t/pocketchip-sdl2-error-on-init/11517/4

**Comment by jlnr** [comment] 2017-05-22 09:10
I suspect that the issue is this code:

https://github.com/gosu/gosu/blob/master/src/Window.cpp#L100-L108

Basically, I create every window in windowed mode first and then centre it, then switch to fullscreen mode.

Can you please try the following steps:
- check out Gosu from git
- remove the first call to `resize` and the call to `SDL_SetWindowPosition`
- build a gem locally using `GOSU_RELEASE_VERSION=9.9.9 rake gem`
- install the gem (I think it'll be `gem install pkg/gosu-9.9.9.gem`)
- retry

**Comment by sci-phi** [comment] 2017-05-25 00:45
OK, I tried making these changes on-device, worked as you said, but it did not resolve it. It may have made the (bad) placement more consistent, but it's still a clipped window with part of the terminal UI showing around. About one in 5 or so tries (just ctrl-q to quit & up-arrow to re-run the script) it will actually go full-screen. It's not every 5th invocation or any other pattern I have noticed.

RE: setWindowPosition... I could not find where the SDL_WINDOWPOS_CENTERED value is set, and I dont see how they would not be the same on any non-square screen, so I think I will rebuild and retry with hand-coded integers to see whether that does anything useful.

**Comment by sci-phi** [comment] 2017-05-25 13:13
I tried replacing everything before SetSwapInterval with hard-coded values to "center" and resize the screen, with similar results (took 7 tries to get fullscreen, bad screen origins are more Up and Left than before)

```
    resize(240, 136, false);
    SDL_SetWindowPosition(shared_window(), 240, 136);
    resize(480, 272, true);
```

I then retried with zeroes for position instead, like so:

    resize(240, 136, false);
    SDL_SetWindowPosition(shared_window(), 0, 0);
    resize(480, 272, true);

That did not fair any better...

**Comment by jlnr** [comment] 2017-05-26 11:56
So just to make sure, if you only call `resize(480, 272, true);`, without the two calls above it, it's still flaky? I don't see why it would work for other people with SDL 2, but not Gosu. :/

**Comment by sci-phi** [comment] 2017-05-29 02:27
Yeah, I am just hacking at this, C/C++ is not my area, hence wanting to use Gosu :)

At any rate : here's the last mod I tried, where I only got 5 full-screen windows out of twenty attempts

```
Gosu::Window::Window(unsigned width, unsigned height, bool fullscreen, double update_interval)
: pimpl(new Impl)
{
    // Even in fullscreen mode, temporarily show the window in windowed mode to centre it.
    // This ensures that the window will be centred correctly when exiting fullscreen mode.
    // Fixes https://github.com/gosu/gosu/issues/369
    // (This will implicitly create graphics() and input(), and make the OpenGL context current.)

    // Per Issue-404 : 
    // Disable initial window open and screen centering...
    // resize(width, height, false);
    // SDL_SetWindowPosition(shared_window(), SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED);
    // Really enable fullscreen if desired.
    // resize(width, height, fullscreen);
    // ===================
    // ISS-404 : TEST/HACK

    // Position at specific coordinates...
    SDL_SetWindowPosition(shared_window(), 0, 0);

    // Resize window to explicit dimensions and fill screen
    resize(480, 272, true);

    // Twenty attempts, Five FS, #s: 7,11,16,18,20
    // ===================
    SDL_GL_SetSwapInterval(1);

    pimpl->update_interval = update_interval;
    
    input().on_button_down = [this](Button button) { button_down(button); };
    input().on_button_up   = [this](Button button) { button_up(button); };
}

```

I then went back to plain C / SDL2 to verify the lower level works reliably in either windowed (mini) or full-screen mode. TLDR; it works fine that way. Seems like a Ruby/Gosu issue but I have no clues really.

![screenshot - 05282017 - 10 13 46 pm](https://cloud.githubusercontent.com/assets/29684/26534680/b1da3266-43f4-11e7-82e5-d9a9a1ad4828.png)
![screenshot - 05282017 - 10 16 13 pm](https://cloud.githubusercontent.com/assets/29684/26534682/b79d3ce8-43f4-11e7-999f-b3d78eb3a524.png)

[boxes-sdl-demo.zip](https://github.com/gosu/gosu/files/1034725/boxes-sdl-demo.zip)

**Comment by sci-phi** [comment] 2017-05-29 02:57
I neglected to include some screenshots from my Gosu attempts previously...

These show:

- that I am using a custom install of Gosu (9.9.666 ... )
- the bad window window that reports as full-screened but is just a 'clipped' corner up and to left
- the good window when it does actually take over full screen sometimes

Hopefully this allows you to track it down eventually. If you do come up with a fix, I'll be happy to test further.

![gosu-debug-01-false-full](https://cloud.githubusercontent.com/assets/29684/26535186/f7bc080a-43f8-11e7-81b4-beaa1d299b02.png)
![gosu-debug-02-upper-left-clipped](https://cloud.githubusercontent.com/assets/29684/26535185/f7b1e320-43f8-11e7-97fa-5d53338f5369.png)
![gosu-debug-03-actual-full](https://cloud.githubusercontent.com/assets/29684/26535187/f7c36c76-43f8-11e7-8504-9a7a3dfbc87c.png)

**Comment by jlnr** [comment] 2017-05-29 10:16
Thanks for the detailed report. I can think of three differences between your SDL 2 example and Gosu that could cause this.

1. Gosu does not use `SDL_WINDOW_FULLSCREEN` (= 1), but `SDL_WINDOW_FULLSCREEN_DESKTOP`.  Can you please try setting `max_flag = SDL_WINDOW_FULLSCREEN_DESKTOP` in boxes.c and retry? Is it broken like Gosu now?
2. Gosu requests a window that uses OpenGL. Set `max_flag = SDL_WINDOW_FULLSCREEN_DESKTOP | SDL_WINDOW_OPENGL` in boxes.c and retry...
3. Gosu creates a hidden window and only shows it later. If the problem is not 1 or 2, then it's probably this.

If the issue is either of these three, then it's not a bug in Gosu, but in SDL 2. I could work around possibility 1 from within Gosu (if running on PocketCHIP, use SDL_WINDOW_FULLSCREEN). But it would be better to get these bugs fixed in SDL itself eventually.

Another thing you can try is to update SDL to the current version (2.0.5) and see if the problem persists...I'm not sure what the exact steps for that are.

Sorry for my clueless troubleshooting, it's really hard to guess where the problem might be without having a device here for debugging. But I'm actually surprised that Gosu works as well as it does :) The Raspberry Pi was a lot more troublesome.

**Comment by jlnr** [comment] 2020-11-16 08:42
I don't have a way to make progress here without a PocketCHIP -> closing due to inactivity

**Closed by jlnr** 2020-11-16 08:42 UTC
Labels: graphics, help wanted
