### ISSUE TITLE
Segmentation fault when trying to use Gosu on Windows

### ISSUE THREAD

**Issue by maximkoo** [gosu/gosu#499] opened 2019-07-26 16:58 UTC
I am getting the following message at any attempt of using Gosu

**C:/RailsInstaller/Ruby25-x64/lib/ruby/gems/2.5.0/gems/gosu-0.14.5-x64-mingw32/lib/gosu/swig_patches.rb:17: [BUG] Segmentation fault
ruby 2.5.5p157 (2019-03-15 revision 67260) [x64-mingw32]**

My code is just this simple

```
require 'gosu'
class Bg<Gosu::Window
	def initialize
		super(600,480)
	end;
end;		
Bg.new.show
```

I use Ruby 2.5.7(p157) and Gosu 0.14.5, but it's the same with Ruby 2.3.3(p222) and Gosu 0.12.1
Windows 10, x64
Probably I have to add the Ruby is installed using RubyInstaller.

I bet it worked well before, I don't know what happened since I touched Ruby the last time.

The rest of the error info:

C:/RailsInstaller/Ruby25-x64/lib/ruby/gems/2.5.0/gems/gosu-0.14.5-x64-mingw32/lib/gosu/swig_patches.rb:17: [BUG] Segmentation fault
ruby 2.5.5p157 (2019-03-15 revision 67260) [x64-mingw32]

-- Control frame information -----------------------------------------------
c:0006 p:---- s:0032 e:000031 CFUNC  :initialize
c:0005 p:0095 s:0024 e:000023 METHOD C:/RailsInstaller/Ruby25-x64/lib/ruby/gems/2.5.0/gems/gosu-0.14.5-x64-mingw32/lib/gosu/swig_patches.rb:17
c:0004 p:0010 s:0014 e:000013 METHOD C:/Users/max/Ruby/Tk/Gosu/bug.rb:4 [FINISH]
c:0003 p:---- s:0010 e:000009 CFUNC  :new
c:0002 p:0033 s:0006 e:000005 EVAL   C:/Users/max/Ruby/Tk/Gosu/bug.rb:7 [FINISH]
c:0001 p:0000 s:0003 E:001c20 (none) [FINISH]

-- Ruby level backtrace information ----------------------------------------
C:/Users/max/Ruby/Tk/Gosu/bug.rb:7:in `<main>'
C:/Users/max/Ruby/Tk/Gosu/bug.rb:7:in `new'
C:/Users/max/Ruby/Tk/Gosu/bug.rb:4:in `initialize'
C:/RailsInstaller/Ruby25-x64/lib/ruby/gems/2.5.0/gems/gosu-0.14.5-x64-mingw32/lib/gosu/swig_patches.rb:17:in `initialize'
C:/RailsInstaller/Ruby25-x64/lib/ruby/gems/2.5.0/gems/gosu-0.14.5-x64-mingw32/lib/gosu/swig_patches.rb:17:in `initialize'

-- C level backtrace information -------------------------------------------
C:\Windows\SYSTEM32\ntdll.dll(ZwWaitForSingleObject+0x14) [0x00007ffc87c05b94]
C:\Windows\System32\KERNELBASE.dll(WaitForSingleObjectEx+0x8f) [0x00007ffc84234abf]
C:\RailsInstaller\Ruby25-x64\bin\x64-msvcrt-ruby250.dll(rb_vm_bugreport+0x2e1) [0x00000000680acae1]
C:\RailsInstaller\Ruby25-x64\bin\x64-msvcrt-ruby250.dll(rb_bug_context+0x6d) [0x0000000067f3bcbd]
C:\RailsInstaller\Ruby25-x64\bin\x64-msvcrt-ruby250.dll(rb_check_safe_obj+0x380) [0x00000000680261b0]
 [0x000000000040234c]
C:\Windows\SYSTEM32\ntdll.dll(_C_specific_handler+0x96) [0x00007ffc87bf6606]
C:\Windows\SYSTEM32\ntdll.dll(_chkstk+0x11d) [0x00007ffc87c0a58d]
C:\Windows\SYSTEM32\ntdll.dll(RtlImageNtHeaderEx+0x483) [0x00007ffc87b9fd23]
C:\Windows\SYSTEM32\ntdll.dll(KiUserExceptionDispatcher+0x3a) [0x00007ffc87c096fa]
C:\Windows\System32\DriverStore\FileRepository\igdlh64.inf_amd64_8a9535cd18c90bc3\ig9icd64.dll(DumpRegistryKeyDefinitions+0xf77e) [0x00007ffc5a40f82e]
C:\Windows\System32\DriverStore\FileRepository\igdlh64.inf_amd64_8a9535cd18c90bc3\ig9icd64.dll(DumpRegistryKeyDefinitions+0x19033) [0x00007ffc5a4190e3]
C:\Windows\System32\DriverStore\FileRepository\igdlh64.inf_amd64_8a9535cd18c90bc3\ig9icd64.dll(DumpRegistryKeyDefinitions+0xf097) [0x00007ffc5a40f147]
C:\Windows\System32\DriverStore\FileRepository\igdlh64.inf_amd64_8a9535cd18c90bc3\ig9icd64.dll(RegisterProcTableCallback+0x1a4b97) [0x00007ffc5a5ebc77]
C:\Windows\System32\DriverStore\FileRepository\igdlh64.inf_amd64_8a9535cd18c90bc3\ig9icd64.dll(DumpRegistryKeyDefinitions+0x43f0a) [0x00007ffc5a443fba]
C:\Windows\System32\DriverStore\FileRepository\igdlh64.inf_amd64_8a9535cd18c90bc3\ig9icd64.dll(DrvCreateLayerContext+0x165) [0x00007ffc5a3fd475]
C:\Windows\SYSTEM32\OPENGL32.dll(wglSwapMultipleBuffers+0x2055) [0x00007ffc6d068495]
C:\Windows\SYSTEM32\OPENGL32.dll(wglCreateLayerContext+0x1d6) [0x00007ffc6d068bd6]
C:\RailsInstaller\Ruby25-x64\lib\ruby\gems\2.5.0\gems\gosu-0.14.5-x64-mingw32\lib64\SDL2.dll(SDL_DYNAPI_entry+0xc4cc0) [0x000000006c824ae0]
C:\RailsInstaller\Ruby25-x64\lib\ruby\gems\2.5.0\gems\gosu-0.14.5-x64-mingw32\lib64\SDL2.dll(SDL_DYNAPI_entry+0xc5505) [0x000000006c825325]
C:\RailsInstaller\Ruby25-x64\lib\ruby\gems\2.5.0\gems\gosu-0.14.5-x64-mingw32\lib64\SDL2.dll(SDL_DYNAPI_entry+0x95c37) [0x000000006c7f5a57]
C:\RailsInstaller\Ruby25-x64\lib\ruby\gems\2.5.0\gems\gosu-0.14.5-x64-mingw32\lib64\SDL2.dll(SDL_DYNAPI_entry+0x97b2f) [0x000000006c7f794f]
C:\RailsInstaller\Ruby25-x64\lib\ruby\gems\2.5.0\gems\gosu-0.14.5-x64-mingw32\lib64\2.5\gosu.so(Init_gosu+0x37828) [0x000000018004b718]
C:\RailsInstaller\Ruby25-x64\lib\ruby\gems\2.5.0\gems\gosu-0.14.5-x64-mingw32\lib64\2.5\gosu.so(Init_gosu+0x3803f) [0x000000018004bf2f]
C:\RailsInstaller\Ruby25-x64\lib\ruby\gems\2.5.0\gems\gosu-0.14.5-x64-mingw32\lib64\2.5\gosu.so(Init_gosu+0x36fc4) [0x000000018004aeb4]
C:\RailsInstaller\Ruby25-x64\lib\ruby\gems\2.5.0\gems\gosu-0.14.5-x64-mingw32\lib64\2.5\gosu.so(Init_gosu+0x36d07) [0x000000018004abf7]
 [0x0000000180002d66]
 [0x000000018000e5ab]
C:\RailsInstaller\Ruby25-x64\bin\x64-msvcrt-ruby250.dll(rb_error_arity+0x121) [0x00000000680904e1]
C:\RailsInstaller\Ruby25-x64\bin\x64-msvcrt-ruby250.dll(rb_mod_module_exec+0x63e) [0x000000006809ebfe]
C:\RailsInstaller\Ruby25-x64\bin\x64-msvcrt-ruby250.dll(rb_mod_module_exec+0xcc0) [0x000000006809f280]
C:\RailsInstaller\Ruby25-x64\bin\x64-msvcrt-ruby250.dll(rb_vm_localjump_error+0x2722) [0x0000000068099532]
C:\RailsInstaller\Ruby25-x64\bin\x64-msvcrt-ruby250.dll(rb_vm_localjump_error+0x676c) [0x000000006809d57c]
C:\RailsInstaller\Ruby25-x64\bin\x64-msvcrt-ruby250.dll(rb_mod_module_eval+0x2fe) [0x00000000680a097e]
C:\RailsInstaller\Ruby25-x64\bin\x64-msvcrt-ruby250.dll(rb_vm_call+0x5b9) [0x00000000680a1499]
C:\RailsInstaller\Ruby25-x64\bin\x64-msvcrt-ruby250.dll(rb_funcallv+0x36) [0x00000000680a1a76]
C:\RailsInstaller\Ruby25-x64\bin\x64-msvcrt-ruby250.dll(rb_undefined_alloc+0x134) [0x0000000067fab684]
C:\RailsInstaller\Ruby25-x64\bin\x64-msvcrt-ruby250.dll(rb_error_arity+0x121) [0x00000000680904e1]
C:\RailsInstaller\Ruby25-x64\bin\x64-msvcrt-ruby250.dll(rb_mod_module_exec+0x63e) [0x000000006809ebfe]
C:\RailsInstaller\Ruby25-x64\bin\x64-msvcrt-ruby250.dll(rb_mod_module_exec+0xcc0) [0x000000006809f280]
C:\RailsInstaller\Ruby25-x64\bin\x64-msvcrt-ruby250.dll(rb_vm_localjump_error+0x2722) [0x0000000068099532]
C:\RailsInstaller\Ruby25-x64\bin\x64-msvcrt-ruby250.dll(rb_vm_localjump_error+0x676c) [0x000000006809d57c]
C:\RailsInstaller\Ruby25-x64\bin\x64-msvcrt-ruby250.dll(rb_call_end_proc+0xe9) [0x0000000067f3fa99]
C:\RailsInstaller\Ruby25-x64\bin\x64-msvcrt-ruby250.dll(ruby_run_node+0x59) [0x0000000067f43419]
 [0x0000000000402d87]
 [0x00000000004013a5]
 [0x000000000040150b]
C:\Windows\System32\KERNEL32.DLL(BaseThreadInitThunk+0x14) [0x00007ffc868084d4]

-- Other runtime information -----------------------------------------------

* Loaded script: C:/Users/max/Ruby/Tk/Gosu/bug.rb

* Loaded features:

    0 enumerator.so
    1 thread.rb
    2 rational.so
    3 complex.so
    4 C:/RailsInstaller/Ruby25-x64/lib/ruby/2.5.0/x64-mingw32/enc/encdb.so
    5 C:/RailsInstaller/Ruby25-x64/lib/ruby/2.5.0/x64-mingw32/enc/trans/transdb.so
    6 C:/RailsInstaller/Ruby25-x64/lib/ruby/2.5.0/x64-mingw32/enc/windows_1251.so
    7 C:/RailsInstaller/Ruby25-x64/lib/ruby/2.5.0/x64-mingw32/rbconfig.rb
    8 C:/RailsInstaller/Ruby25-x64/lib/ruby/2.5.0/rubygems/compatibility.rb
    9 C:/RailsInstaller/Ruby25-x64/lib/ruby/2.5.0/rubygems/defaults.rb
   10 C:/RailsInstaller/Ruby25-x64/lib/ruby/2.5.0/rubygems/deprecate.rb
   11 C:/RailsInstaller/Ruby25-x64/lib/ruby/2.5.0/rubygems/errors.rb
   12 C:/RailsInstaller/Ruby25-x64/lib/ruby/2.5.0/rubygems/version.rb
   13 C:/RailsInstaller/Ruby25-x64/lib/ruby/2.5.0/rubygems/requirement.rb
   14 C:/RailsInstaller/Ruby25-x64/lib/ruby/2.5.0/rubygems/platform.rb
   15 C:/RailsInstaller/Ruby25-x64/lib/ruby/2.5.0/rubygems/basic_specification.rb
   16 C:/RailsInstaller/Ruby25-x64/lib/ruby/2.5.0/rubygems/stub_specification.rb
   17 C:/RailsInstaller/Ruby25-x64/lib/ruby/2.5.0/rubygems/util/list.rb
   18 C:/RailsInstaller/Ruby25-x64/lib/ruby/2.5.0/x64-mingw32/stringio.so
   19 C:/RailsInstaller/Ruby25-x64/lib/ruby/2.5.0/uri/rfc2396_parser.rb
   20 C:/RailsInstaller/Ruby25-x64/lib/ruby/2.5.0/uri/rfc3986_parser.rb
   21 C:/RailsInstaller/Ruby25-x64/lib/ruby/2.5.0/uri/common.rb
   22 C:/RailsInstaller/Ruby25-x64/lib/ruby/2.5.0/uri/generic.rb
   23 C:/RailsInstaller/Ruby25-x64/lib/ruby/2.5.0/uri/ftp.rb
   24 C:/RailsInstaller/Ruby25-x64/lib/ruby/2.5.0/uri/http.rb
   25 C:/RailsInstaller/Ruby25-x64/lib/ruby/2.5.0/uri/https.rb
   26 C:/RailsInstaller/Ruby25-x64/lib/ruby/2.5.0/uri/ldap.rb
   27 C:/RailsInstaller/Ruby25-x64/lib/ruby/2.5.0/uri/ldaps.rb
   28 C:/RailsInstaller/Ruby25-x64/lib/ruby/2.5.0/uri/mailto.rb
   29 C:/RailsInstaller/Ruby25-x64/lib/ruby/2.5.0/uri.rb
   30 C:/RailsInstaller/Ruby25-x64/lib/ruby/2.5.0/rubygems/specification.rb
   31 C:/RailsInstaller/Ruby25-x64/lib/ruby/2.5.0/rubygems/exceptions.rb
   32 C:/RailsInstaller/Ruby25-x64/lib/ruby/site_ruby/2.5.0/ruby_installer/runtime/singleton.rb
   33 C:/RailsInstaller/Ruby25-x64/lib/ruby/site_ruby/2.5.0/ruby_installer/runtime.rb
   34 C:/RailsInstaller/Ruby25-x64/lib/ruby/site_ruby/2.5.0/ruby_installer/runtime/msys2_installation.rb
   35 C:/RailsInstaller/Ruby25-x64/lib/ruby/2.5.0/x64-mingw32/fiddle.so
   36 C:/RailsInstaller/Ruby25-x64/lib/ruby/2.5.0/fiddle/function.rb
   37 C:/RailsInstaller/Ruby25-x64/lib/ruby/2.5.0/fiddle/closure.rb
   38 C:/RailsInstaller/Ruby25-x64/lib/ruby/2.5.0/fiddle.rb
   39 C:/RailsInstaller/Ruby25-x64/lib/ruby/site_ruby/2.5.0/ruby_installer/runtime/dll_directory.rb
   40 C:/RailsInstaller/Ruby25-x64/lib/ruby/2.5.0/x64-mingw32/enc/utf_16le.so
   41 C:/RailsInstaller/Ruby25-x64/lib/ruby/2.5.0/x64-mingw32/enc/trans/utf_16_32.so
   42 C:/RailsInstaller/Ruby25-x64/lib/ruby/2.5.0/rubygems/defaults/operating_system.rb
   43 C:/RailsInstaller/Ruby25-x64/lib/ruby/2.5.0/rubygems/dependency.rb
   44 C:/RailsInstaller/Ruby25-x64/lib/ruby/2.5.0/rubygems/core_ext/kernel_gem.rb
   45 C:/RailsInstaller/Ruby25-x64/lib/ruby/2.5.0/monitor.rb
   46 C:/RailsInstaller/Ruby25-x64/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb
   47 C:/RailsInstaller/Ruby25-x64/lib/ruby/2.5.0/rubygems.rb
   48 C:/RailsInstaller/Ruby25-x64/lib/ruby/2.5.0/rubygems/path_support.rb
   49 C:/RailsInstaller/Ruby25-x64/lib/ruby/gems/2.5.0/gems/did_you_mean-1.2.0/lib/did_you_mean/version.rb
   50 C:/RailsInstaller/Ruby25-x64/lib/ruby/gems/2.5.0/gems/did_you_mean-1.2.0/lib/did_you_mean/core_ext/name_error.rb
   51 C:/RailsInstaller/Ruby25-x64/lib/ruby/gems/2.5.0/gems/did_you_mean-1.2.0/lib/did_you_mean/levenshtein.rb
   52 C:/RailsInstaller/Ruby25-x64/lib/ruby/gems/2.5.0/gems/did_you_mean-1.2.0/lib/did_you_mean/jaro_winkler.rb
   53 C:/RailsInstaller/Ruby25-x64/lib/ruby/gems/2.5.0/gems/did_you_mean-1.2.0/lib/did_you_mean/spell_checker.rb
   54 C:/RailsInstaller/Ruby25-x64/lib/ruby/2.5.0/delegate.rb
   55 C:/RailsInstaller/Ruby25-x64/lib/ruby/gems/2.5.0/gems/did_you_mean-1.2.0/lib/did_you_mean/spell_checkers/name_error_checkers/class_name_checker.rb
   56 C:/RailsInstaller/Ruby25-x64/lib/ruby/gems/2.5.0/gems/did_you_mean-1.2.0/lib/did_you_mean/spell_checkers/name_error_checkers/variable_name_checker.rb
   57 C:/RailsInstaller/Ruby25-x64/lib/ruby/gems/2.5.0/gems/did_you_mean-1.2.0/lib/did_you_mean/spell_checkers/name_error_checkers.rb
   58 C:/RailsInstaller/Ruby25-x64/lib/ruby/gems/2.5.0/gems/did_you_mean-1.2.0/lib/did_you_mean/spell_checkers/method_name_checker.rb
   59 C:/RailsInstaller/Ruby25-x64/lib/ruby/gems/2.5.0/gems/did_you_mean-1.2.0/lib/did_you_mean/spell_checkers/key_error_checker.rb
   60 C:/RailsInstaller/Ruby25-x64/lib/ruby/gems/2.5.0/gems/did_you_mean-1.2.0/lib/did_you_mean/spell_checkers/null_checker.rb
   61 C:/RailsInstaller/Ruby25-x64/lib/ruby/gems/2.5.0/gems/did_you_mean-1.2.0/lib/did_you_mean/formatters/plain_formatter.rb
   62 C:/RailsInstaller/Ruby25-x64/lib/ruby/gems/2.5.0/gems/did_you_mean-1.2.0/lib/did_you_mean.rb
   63 C:/RailsInstaller/Ruby25-x64/lib/ruby/2.5.0/rubygems/bundler_version_finder.rb
   64 C:/RailsInstaller/Ruby25-x64/lib/ruby/2.5.0/rubygems/util.rb
   65 C:/RailsInstaller/Ruby25-x64/lib/ruby/site_ruby/2.5.0/ruby_installer.rb
   66 C:/RailsInstaller/Ruby25-x64/lib/ruby/gems/2.5.0/gems/gosu-0.14.5-x64-mingw32/lib64/2.5/gosu.so
   67 C:/RailsInstaller/Ruby25-x64/lib/ruby/gems/2.5.0/gems/gosu-0.14.5-x64-mingw32/lib/gosu/swig_patches.rb
   68 C:/RailsInstaller/Ruby25-x64/lib/ruby/gems/2.5.0/gems/gosu-0.14.5-x64-mingw32/lib/gosu/patches.rb
   69 C:/RailsInstaller/Ruby25-x64/lib/ruby/gems/2.5.0/gems/gosu-0.14.5-x64-mingw32/lib/gosu/compat.rb
   70 C:/RailsInstaller/Ruby25-x64/lib/ruby/gems/2.5.0/gems/gosu-0.14.5-x64-mingw32/lib/gosu.rb

[NOTE]
You may have encountered a bug in the Ruby interpreter or extension libraries.
Bug reports are welcome.
For details: http://www.ruby-lang.org/bugreport.html

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.

**Comment by jlnr** [comment] 2019-07-26 22:37
I don't know why OpenGL shows up in the _middle_ of the stacktrace, but it does show up:

> C:\Windows\SYSTEM32\OPENGL32.dll(wglCreateLayerContext+0x1d6) [0x00007ffc6d068bd6]

Typically these kinds of issues are caused by broken OpenGL drivers on Windows. Do other OpenGL-based games work, say SuperTuxKart? (I think they have no Direct3D backend)

Updating or reinstalling the drivers might fix this. It would be good to reduce Gosu's reliance on OpenGL, but that's easier said than done :|

**Comment by maximkoo** [comment] 2019-07-27 05:38
Thank you for the response!

SuperTuxCart crashes too:

![изображение](https://user-images.githubusercontent.com/12088108/61990446-84e1c300-b049-11e9-9cb4-aba203fd2391.png)

I will try to reinstall everything related to Ruby. It worked fine months ago, including Gosu. I want to add that Chipmunk gem fails to install too, it crashes when building those notorious native extensions.

**Comment by maximkoo** [comment] 2019-07-27 11:47
The problem was the video adapter driver. I rolled back to the older 22.20.16.4815 driver version for my Intel 630, and Gosu works fine, as well as SuperTuxCart.

**Comment by jlnr** [comment] 2019-07-27 17:36
Great to hear :) I'll close this issue, even though I'm sure it'll happen again and again until I bundle something like ANGLE with Gosu.

**Closed by jlnr** 2019-07-27 17:36 UTC
