### ISSUE TITLE
odd behavior involving fullscreen on windows

### ISSUE THREAD

**Issue by lonelylittlelucas** [gosu/gosu#500] opened 2019-07-29 02:11 UTC
im not sure if its the way that i made this, but i tried to make a menu screen with clickable buttons

my original idea was to have a ui button call a proc 

```ruby
class Ui_button
    def initialize(message,font_size,x,y,width,height,color,proc)
        @message=message
        @font=Gosu::Font.new(font_size)
        @x=x
        @y=y
        @width=width
        @height=height
        @proc=proc
        @color=color
    end
    def test(ui)
        if ui.mouse_x>@x&&ui.mouse_x<@x+@width&&ui.mouse_y>@y&&ui.mouse_y<@y+@height&&Gosu.button_down?(Gosu::MS_LEFT)
            self.click()
        end
    end
    def click()
        @proc.call()
    end
    def draw()
        Gosu.draw_rect(@x,@y,@width,@height,@color)
        @font.draw_text(@message,@x,@y,0)
    end
end
```
with this button, i set up a way of being able to change the view, basically, have the window, and then a class `room` that is called

`main.rb`
```ruby
#im leaving out the requires
class Ui < Gosu::Window
    attr_accessor :room, :cursor
    def initialize()
        super(1024,1024,fullscreen=true)
        @room=Menu.new(self)
        @cursor=true
    end
    def needs_cursor?
        @cursor
    end
    def button_down(id)
        @room.button(id)
    end
    def update()
        @room.update()
    end
    def draw()
        @room.draw()
    end
end
ui=Ui.new
ui.show
```

now, when i make the menu class 
```ruby
class Menu
    def initialize(parent,*args)
        @parent=parent
        @fpsfont=Gosu::Font.new(16)
        @menu_font=Gosu::Font.new(64)
        @elem=[]
        @elem.push(Ui_button.new("Exit",64,32,192,128,64,Gosu::Color.argb(0xff_ff0000),Proc.new{@parent.close!}))
        @elem.push(Ui_button.new("Test",64,32,257,128,64,Gosu::Color.argb(0xff_00ffab),Proc.new{@parent.room=Dev_test.new(@parent)}))
    end
    def button(id)
    end
    def update()
        @elem.each do |elem|
            elem.test(@parent)
        end
    end
    def draw()
        @fpsfont.draw_text(Gosu.fps,0,0,0)
        @menu_font.draw_text("Menu",32,128,1)
        @elem.each do |elem|
            elem.draw()
        end
    end
end
```
i click on the buttons and they function somewhat like i want, but whenever the close method is called in the main menu, it inconsistently freezes, and if i press esc in the test room, it calls parent.close, and the computer freezes for a bit.
I tried my best to give as much info for you to fix this problem. thank you

**Comment by lonelylittlelucas** [comment] 2019-07-29 03:28
after further investigation, i have confirmed that fullscreen is the cause of this bug

**Comment by jlnr** [comment] 2019-07-29 11:02
On which operating system do you experience the freezes?

**Comment by lonelylittlelucas** [comment] 2019-08-01 20:22
im on windows

**Comment by lonelylittlelucas** [comment] 2019-08-01 20:36
some more info that i think might be important, it only happened once i added the second button

**Comment by jlnr** [comment] 2019-08-24 19:15
I've just tried to reproduce this issue on Windows 10, with an Nvidia card, and using Ruby 2.6. Clicking the Exit button immediately closes the game, even in fullscreen mode. Are there any extra steps I need to do after cloning your repository?

Do other OpenGL games have similar issues (e.g. Super Tux Kart)?

**Comment by jlnr** [comment] 2019-08-27 07:33
No, the Gem is only necessary if you want to use OpenGL from Ruby. Gosu and Super Tux Kart both use OpenGL in their respective C++ code.

**Comment by jlnr** [comment] 2019-08-27 11:44
Yes, I have tested it in fullscreen mode.

Every mainstream GPU made in the last 15 years will be strong enough to run your code, as long as your OpenGL drivers work as expected - that's why I've asked about SuperTuxKart, but any OpenGL game will do the trick. I don't know why so many Windows systems have broken OpenGL drivers, but that's probably the #1 source of problems with Gosu right now.

**Comment by jlnr** [comment] 2019-10-06 15:49
Closing this issue, since I don't think there's anything I can do here except replace OpenGL altogether (e.g. by using ANGLE). Sorry, I wish there was a simpler fix for these driver issues :/

**Closed by jlnr** 2019-10-06 15:49 UTC
