### ISSUE TITLE
mouse_x/mouse_y values incorrect in fullscreen on macOS

### ISSUE THREAD

**Issue by netmute** [gosu/gosu#455] opened 2018-06-18 16:27 UTC
I have a 1440x900 window. In window mode the bottom right mouse position is 1440x900, as expected. In fullscreen mode the bottom right mouse position is 810x506.
I have no idea what's going on 🤪

**Comment by jlnr** [comment] 2018-06-19 08:37
Whoops, not sure how I could miss this for so long. Will look into it as part of v0.14

**Comment by jlnr** [comment] 2018-09-08 14:57
SDL_GetGlobalMouseState() seems to be broken on macOS. First step: Send a bug report.

**Comment by jlnr** [comment] 2018-09-09 18:48
I don't think this was related to HiDPI, but to multi-monitor support in general. Fixed by #459

**Closed by jlnr** 2018-09-09 18:48 UTC
Labels: graphics, help wanted, platform-mac

**Comment by jlnr** [comment] 2018-09-09 18:51
It seems that this will be fixed by #459. I can't reproduce this on macOS anymore.
