### ISSUE TITLE
DLL clashes where they shouldn't happen

### ISSUE THREAD

**Issue by erunks** [gosu/gosu#320] opened 2016-03-09 03:49 UTC
I am on a 64bit version of Windows 8.1 and I just upgraded my version of ruby today. After my upgrade I found out with much pain, after removing previous version of ruby (2.1.7 I believe), that gosu doesn't seem to work on my new version of ruby. Is there some fix out there that I'm over looking or am I just going to have to wait for a fix? This is the error I receive: 

> C:/Ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require': 127: The specified procedure could not be found.   - C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/gosu-0.10.6-x64-mingw32/lib64/2.2/gosu.so (LoadError)
>   from C:/Ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in`require'
>   from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/gosu-0.10.6-x64-mingw32/lib/gosu.rb:16:in `<top (required)>'
>   from C:/Ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:127:in`require'
>   from C:/Ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:127:in `rescue in require'
>   from C:/Ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:40:in`require'
>   from C:/Users/Eddie/Documents/NetBeansProjects/platform_side_project/lib/main.rb:1:in `<main>'

Edit:
Just tried some earlier versions of gosu and I got the new ruby to work with gosu -v 0.9.2. Any reason why ruby 2.2.4 would work with this earlier version of gosu and not the newest version?

**Comment by RyuGe** [comment] 2016-03-09 06:59
Works for me. Ruby 2.2.4p230 and Ruby 0.10.6. I use Windows 10 64bit.

**Comment by jlnr** [comment] 2016-03-09 10:44
One big difference between Gosu 0.9.x and 0.10.x is that I'm compiling the latter with Visual Studio 2015. The 0.9.x series used Visual Studio 2010.

> The specified procedure could not be found

That sounds like a DLL might be missing. Can you please download [Dependency Walker](http://www.dependencywalker.com) in the 64-bit version, copy `gosu/lib64/2.2/gosu.so` up into the `lib64` directory, and then open `gosu.so` with Dependency Walker? Do you see any errors other than the two in this screenshot?

![depends](https://cloud.githubusercontent.com/assets/70772/13632863/365ff7f4-e5ec-11e5-8ccc-e98f36d87614.png)

(It's unbelievable how much easier this could be if Windows' error message included the DLL/function that was missing...sigh :()

**Comment by AntonioCheca** [comment] 2016-04-08 21:25
I have exactly the same problem, and tried to run Dependency Walker with gosu.so copied. Here is the screenshot:

![dependency_dll](https://cloud.githubusercontent.com/assets/9285650/14397753/b051f462-fddf-11e5-8bfe-41917ee42a5e.jpg)

I guess the missing DLL is x64-msvcrt-ruby220.dll. No idea how to get it, though.

**Comment by jlnr** [comment] 2016-04-08 21:52
That DLL should come with Ruby, I think it's in the Ruby\bin directory. If you copy it next to `gosu.so`, Dependency Walker should find it.
Hmm, no idea what else could be missing.

**Comment by AntonioCheca** [comment] 2016-04-08 23:10
It seems that the problem wasn't a missing dll, but a duplicate file (SDL2.DLL). Removing the old one solved my dependency errors and now it runs fine. Not sure if this is the only way to solve the problem, but hope it helps.

**Comment by jlnr** [comment] 2016-04-09 07:52
Oh, that's interesting. Where did the duplicate file live? Gosu should, in theory, prioritise its own bundled DLL files.

**Comment by AntonioCheca** [comment] 2016-04-09 09:40
It was on C:\Windows\System32

**Comment by jlnr** [comment] 2016-04-09 09:42
Interesting, I'll try to reproduce this some time!

**Comment by remcopeereboom** [comment] 2016-04-13 13:24
I have the same issue. I'm using Ruby 2.3.0p0 x-64-Mingw on Windows 10 and trying to run Gosu 0.10.6 x64-Mingw. I haven't had problems before when I was running ruby 2.2, but I might have been running a different Gosu version.

**Comment by jlnr** [comment] 2016-04-13 14:59
@remcopeereboom no, that is #230 :)

**Comment by remcopeereboom** [comment] 2016-04-13 15:01
> @remcopeereboom no, that is #230 :)

@jlnr How so? I can't see any relation ship between them.

**Comment by jlnr** [comment] 2016-04-13 15:08
@remcopeereboom Sorry for the typo, I've corrected my reply.

**Comment by jlnr** [comment] 2018-09-10 10:31
Gosu will soon require Ruby 2.3+. Closing this issue because the build process might have changed from Ruby 2.2 to the current 2.5 builds.

**Closed by jlnr** 2018-09-10 10:31 UTC
Labels: platform-windows
