### ISSUE TITLE
Gosu fail on load in ruby 3.1

### ISSUE THREAD

**Issue by fitmap** [gosu/gosu#611] opened 2022-01-20 07:25 UTC
C:\>gem i gosu
Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions. This could take a while...
Successfully installed gosu-1.3.0
Parsing documentation for gosu-1.3.0
Done installing documentation for gosu after 0 seconds
1 gem installed

C:\>shou.rb
<internal:C:/Ruby/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require': 126: �Ҳ���ָ����ģ�顣   - C:/Ruby/lib/ruby/gems/3.1.0/gems/gosu-1.3.0/lib/gosu.so (LoadError)
        from <internal:C:/Ruby/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from C:/Ruby/lib/ruby/gems/3.1.0/gems/gosu-1.3.0/lib/gosu.rb:22:in `<top (required)>'
        from <internal:C:/Ruby/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:160:in `require'
        from <internal:C:/Ruby/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:160:in `rescue in require'
        from <internal:C:/Ruby/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:149:in `require'
        from C:/R/Hike/draw.rb:20:in `<top (required)>'
        from <internal:C:/Ruby/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:C:/Ruby/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from C:/R/Hike/shou.rb:23:in `<main>'
<internal:C:/Ruby/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- gosu (LoadError)
        from <internal:C:/Ruby/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from C:/R/Hike/draw.rb:20:in `<top (required)>'
        from <internal:C:/Ruby/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:C:/Ruby/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from C:/R/Hike/shou.rb:23:in `<main>'

Note: It is okay in Ruby 3.0

**Comment by fitmap** [comment] 2022-01-20 07:30
When I use Guso in Ruby 3.0, the version of Guso is 1.2.0.

**Comment by fitmap** [comment] 2022-01-20 07:37
After I go back to Gosu 1.2.0, the error is same.

C:>gem uni gosu --version '=1.3.0'
Successfully uninstalled gosu-1.3.0

C:>gem i gosu --version '=1.2.0'
Fetching gosu-1.2.0.gem
Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions. This could take a while...
Successfully installed gosu-1.2.0
Parsing documentation for gosu-1.2.0
Installing ri documentation for gosu-1.2.0
Done installing documentation for gosu after 1 seconds
1 gem installed

**Comment by fitmap** [comment] 2022-01-20 11:58
After I rollback to Ruby 3.0, Gosu works fine.
C:>ruby -v
ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x64-mingw32]

**Comment by cyberarm** [comment] 2022-01-20 16:54
Thanks for reporting this @fitmap!
This issue is caused by Ruby 3.1 having changed the `RUBY_PLATFORM` string that the gosu's dll loader uses to detect that it is running under windows. I should have a patch for this soon.

**Comment by jlnr** [comment] 2022-01-20 17:42
Fixed in #612, thanks @cyberarm :+1:

I'll try to push out a new release tomorrow.

**Comment by jlnr** [comment] 2022-01-21 21:53
Should be fixed in the newly released Gosu 1.4.0.

**Closed by jlnr** 2022-01-21 21:53 UTC
